# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('stylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist.Stylist'),
        ),
    ]
