# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stylist',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
