from rest_framework import serializers

from api.utils.serializers.UserSerializer import UserSerializer
from api.utils.serializers.PortfolioHaircutSerializer import PortfolioHaircutSerializer
from api.utils.serializers.GlobalMenuSerializer import GlobalMenuSerializer
from api.utils.serializers.StylistMenuSerializer import StylistMenuSerializer
from api.utils.serializers.StylistSerializer import StylistSerializer
from api.utils.serializers.AppointmentSerializer import AppointmentSerializer
from api.utils.serializers.CalendarEventSerializer import CalendarEventSerializer
from api.utils.serializers.ShiftSerializer import ShiftSerializer
